#!/bin/bash
#########################################
#
#  traduke [lingvo] [dosiero]*
#
# unu argomento :
#    tradukas el esperanto al la lingvo de la argumento.
# 
# sen argumento :
#    se laborlingvo ne estas esperanto : traduki al esperanto
#    poste tradukas ĉion al la aliaj lingvoj.
#
#########################################


. $(dirname $(readlink -f $0))/lib/head

cd "$BASEDIR"
cd ..

LABORLINGVO=`grep "laborlingvo:" _config.yml|awk '{print $2;}'`

lang0=eo

if [ $# -gt 0 ] ; then
  LINGVOJ="$1"
else
  LINGVOJ=$(grep "^..:$" _data/languages.yml|sed "s/:$//"|grep -v $lang0)
  if [ $LABORLINGVO != eo -a $# -ge 0 ] ; then
     _scripts/lib/al_eo $LABORLINGVO
  fi
fi

cd eo

if [ $# -gt 1 ] ; then 
  shift
  echo "$@"
else
  find . -type f -name "*.md" -o -name "*.yml"|egrep -v "/_drafts/|.backup$|.swp$"
fi | while read FIC
do
  EXT="${FIC##*.}"
  case "$EXT" in
	yml)
	  OPTIONS="-f yaml" 
          ;;
	*)
	  OPTIONS="-f text --option markdown -o neverwrap" 
          ;;
  esac
  if [ ! -f "../_locale/${lang0}/${FIC}.pot" ]
  then
    po4a-gettextize -m "${FIC}" --master-charset "UTF-8" $OPTIONS --po "../_locale/${lang0}/${FIC}.pot"
  else
    if [ "../_locale/${lang0}/${FIC}.pot" -ot "${FIC}" ]
    then
      po4a-updatepo --wrap-po no -m "${FIC}" --master-charset "UTF-8" $OPTIONS --po "../_locale/${lang0}/${FIC}.pot"
    fi
  fi
  for lang in $LINGVOJ
  do
    # ne traduki se fina dosiero ekzistas, sed ne la "po" dosiero 
    if [ ! -f "../_locale/${lang}/${FIC}.po" -a -f "../${lang}/${FIC}" ]
    then
      continue;
    fi
    if [ ! -d `dirname "../_locale/${lang}/${FIC}.po"` ]
    then
      mkdir -p `dirname "../_locale/${lang}/${FIC}.po"`
    fi
    if [ ! -f "../_locale/${lang}/${FIC}.po" ]
    then
      echo "`trad 'krei traduko al'` ${lang} ';' ${FIC} '.' "
      cat "../_locale/${lang0}/${FIC}.pot"|sed "s/^\"Language: \\\n\"/\"Language: "${lang}"\\\n\"/" > "../_locale/${lang}/${FIC}.po"
    elif [ "../_locale/${lang}/${FIC}.po" -ot "../_locale/${lang0}/${FIC}.pot" ]
    then
      echo "ĝisdatigi traduko ${FIC} al ${lang}"
      po4a-updatepo --msgmerge-opt --no-fuzzy-matching --wrap-po no -m "${FIC}" --master-charset "UTF-8" $OPTIONS --po "../_locale/${lang}/${FIC}.po"
    fi
    ../_scripts/lib/traduki_po.sh "../_locale/${lang}/${FIC}.po"
    if diff "../_locale/${lang}/${FIC}.po.nova" "../_locale/${lang}/${FIC}.po" >/dev/null
    then
      rm "../_locale/${lang}/${FIC}.po.nova"
    else
      echo ĝisdatigi _locale/${lang}/${FIC}.po
      mv "../_locale/${lang}/${FIC}.po.nova" "../_locale/${lang}/${FIC}.po"
    fi
    if [ ! -d `dirname "../${lang}/${FIC}"` ]
    then
      mkdir -p `dirname "../${lang}/${FIC}"`
    fi
    if [ "../${lang}/${FIC}" -ot "../_locale/${lang}/${FIC}.po" ]
    then
      echo "tradukante ${FIC} al ${lang}"
      #grep -v "^#, fuzzy" ../_locale/${lang}/${FIC}.po >../_locale/temp$$.po
      cat "../_locale/${lang}/${FIC}.po"|sed "s/^#, fuzzy/#/" >../_locale/temp$$.po
      po4a-translate $OPTIONS -m "${FIC}" --master-charset "UTF-8"  --po ../_locale/temp$$.po --localized "../${lang}/${FIC}" --localized-charset "UTF-8" -k 0
      if egrep -m 1 "^#.*, fuzzy" "../_locale/${lang}/${FIC}.po" >/dev/null
      then
       true
      else
       sed -i "s/^lang-niv: auto$/lang-niv: homa/" "../${lang}/${FIC}"
      fi
      rm ../_locale/temp$$.po
    fi
  done
done

cd ..

cat /dev/null >_data/translations.yml
for lang in `grep "^..:$" _data/languages.yml|sed "s/:$//"`
do
  cat $lang/_data/site-translations.yml|grep -v "^---$"|sed "s/^lang:\$/${lang}:/" >> _data/translations.yml
done


sleep 2

